# Change these first
owner: Lehnux # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Blog
    url: https://lehnux.wordpress.com/
  - name: Nextcloud Hosted
    url: https://cloud.lehnux.net
  - name: Blog Alias
    url: https://blog.lehnux.net/
  - name: HA Proxy
    url: https://proxy.lehnux.net/
  - name: Sabnzb
    url: https://sabnzb.lehnux.net/
  - name: Radarr
    url: https://radarr.lehnux.net/
  - name: Plex Media Server
    url: https://plex.lehnux.net/
  - name: Sonarr
    url: https://sonarr.lehnux.net/
  - name: Router
    url: https://rtr.lehnux.net/
  - name: VPN Service
    url: https://vpn.lehnux.net
  - name: Nextcloud Internal
    url: https://next.lehnux.net
assignees: # Users to assign downtime issues (optional)
  - Lehnux
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.lehnux.net
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Lehnux
  introTitle: "This status webpage monitors the status of the services provided by Lehnux."
  introMessage: This status page uses **real-time** data from a [GitHub repository](https://github.com/upptime/upptime).
  theme: dark
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
